jobs:
  - job: RunChecks
    displayName: 'Run Code Checks'
    steps:
      - checkout: self
        fetchDepth: 0
        displayName: 'Disable fetchDepth'

      - task: NodeTool@0
        inputs:
          versionSpec: '20.x'
        displayName: 'Install Node.js'

      - script: npm install
        displayName: 'Install Project Dependencies'

      - script: npm run test:coverage
        displayName: 'Run Unit Tests with Coverage'

      - script: |
          echo "sonar.projectKey=$(PROJECT_KEY)" > sonar-project.properties
          echo "sonar.organization=$(ORGANIZATION)" >> sonar-project.properties
          echo "sonar.javascript.lcov.reportPaths=$(LCOV_REPORT_PATHS)" >> sonar-project.properties
          echo "sonar.typescript.tsconfigPaths=$(TS_CONFIG_PATHS)" >> sonar-project.properties
        displayName: 'Set SonarQube properties'

      - script: |
          echo "Content of sonar-project.properties:"
          cat sonar-project.properties
        displayName: 'Print sonar-project.properties'

      - task: SonarCloudPrepare@2
        displayName: 'Prepare SonarCloud'
        inputs:
          SonarCloud: 'SonarCloud Service Connection'
          organization: 'hsandoval'
          scannerMode: 'CLI'
          configMode: 'file'
          extraProperties: |
            sonar.exclusions=**/node_modules/**,**/dist/**

      - task: SonarCloudAnalyze@2
        inputs:
          jdkversion: 'JAVA_HOME_17_X64'
        displayName: 'Run SonarCloud Analyze'

      - task: SonarCloudPublish@2
        displayName: 'Publish Quality Gate Result'
        inputs:
          pollingTimeoutSec: '300'

      - task: PublishTestResults@2
        displayName: 'Publish Unit Test Results'
        condition: succeededOrFailed()
        inputs:
          testResultsFormat: 'JUnit'
          testResultsFiles: '**/test-results/jest-junit.xml'
          mergeTestResults: true
          testRunTitle: 'Unit Tests'

      - task: PublishCodeCoverageResults@2
        displayName: 'Publish Unit Test Results'
        condition: succeededOrFailed()
        inputs:
          summaryFileLocation: '**/coverage/lcov.info'
