trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

resources:
  - repo: self

parameters:
  - name: runCodeQuality
    displayName: Run CodeQuality
    type: boolean
    default: true

variables:
  - group: SonarQube
  - name: acrConnection
    value: 'HasDevWK'
  - name: dockerImageRepo
    value: 'jobmagnetic/frontend'
  - name: acrName
    value: 'hasacr.azurecr.io'
  - name: dockerfilePath
    value: '$(Build.SourcesDirectory)/dockerfile'
  - name: tag
    value: '$(Build.BuildId)'

stages:
  - stage: CodeQuality
    displayName: 'Code Quality and Testing'
    condition: eq('${{ parameters.runCodeQuality }}', true)
    jobs:
      - template: templates/code-quality-template.yml

  - stage: SetVersion
    dependsOn: CodeQuality
    condition: or(eq('${{ parameters.runCodeQuality }}', false), succeeded('CodeQuality'))
    jobs:
      - job: GitVersion
        displayName: 'Execute GitVersion'
        steps:
          - template: templates/execute-gitversion-template.yml

  - stage: ImageBuild
    dependsOn: SetVersion
    condition: or(eq('${{ parameters.runCodeQuality }}', false), succeeded('CodeQuality'))
    displayName: 'Build and Push Docker Image'
    jobs:
      - job: BuildImage
        displayName: 'Build and Push Image'
        variables:
          gitVersionTag: $[stageDependencies.SetVersion.GitVersion.outputs['GitVersion.tag'] ]
        steps:
          - script: |
              echo "GitVersion: $(gitVersionTag)"
            displayName: 'Check GitVersion'

          - task: Docker@2
            displayName: 'Build and Push to Registry'
            inputs:
              command: buildAndPush
              repository: $(dockerImageRepo)
              dockerfile: $(dockerfilePath)
              containerRegistry: $(acrConnection)
              tags: |
                $(gitVersionTag)

  - stage: PublishArtifact
    dependsOn:
      - SetVersion
      - ImageBuild
    displayName: 'Publish Build Artifact'
    variables:
      gitVersionTag: $[stageDependencies.SetVersion.GitVersion.outputs['GitVersion.tag'] ]
    jobs:
      - job: PublishBuildId
        displayName: 'Publish Build ID Artifact'
        steps:
          - script: |
              echo "GitVersion: $(gitVersionTag)"
            displayName: 'Check GitVersion'

          - script: echo $(gitVersionTag) > $(Build.ArtifactStagingDirectory)/buildId.txt
            displayName: 'Save TagVersion to File'

          - task: PublishBuildArtifacts@1
            displayName: 'Publish artifact'
            inputs:
              PathtoPublish: '$(Build.ArtifactStagingDirectory)'
              ArtifactName: 'WebApp'
              publishLocation: 'Container'
