trigger: none

pool:
  vmImage: 'ubuntu-latest'

resources:
  pipelines:
    - pipeline: BuildPipelineArtifacts
      source: FrontEnd/WebApp/ContinuousIntegration
      trigger:
        branches:
          include:
            - master

variables:
  webAppName: 'JobMagneticDev'
  azureServiceConnection: 'HasDevWK'
  dockerImageRepo: 'jobmagnetic/frontend'
  acrName: 'hasacr.azurecr.io'
  resourceName: 'HasDev'

stages:
  - stage: Deploy
    displayName: 'Deploy to DEV'
    jobs:
      - deployment: Deploy
        environment: 'DeployDev'
        strategy:
          runOnce:
            deploy:
              steps:
                - template: templates/deploy-template.yml
                  parameters:
                    projectId: '$(resources.pipeline.BuildPipelineArtifacts.projectID)'
                    pipelineId: '$(resources.pipeline.BuildPipelineArtifacts.pipelineID)'
                    runId: '$(resources.pipeline.BuildPipelineArtifacts.runID)'
                    artifactName: 'WebApp'
                    targetPath: '$(Pipeline.Workspace)/downloaded_artifact'
                    appServiceName: $(webAppName)
                    azureSubscription: $(azureServiceConnection)
                    imageRepository: $(dockerImageRepo)
                    containerRegistry: $(acrName)
                    resourceGroupName: $(resourceName)
