trigger: none

pool:
  vmImage: 'ubuntu-latest'

resources:
  pipelines:
    - pipeline: azure-pipelines-CI
      source: FrontEnd/CI
      project: MySite
      trigger:
        branches:
          include:
            - develop

variables:
  azureResourceServiceConnection: 'Azure Resource Manager Connection'
  imageRepository: 'mysitefrontend'
  containerRegistry: 'hasacr.azurecr.io'
  resourceGroupName: 'HasDev'

stages:
  - stage: DeployDev
    displayName: 'Deploy to DEV'
    jobs:
      - deployment: DeployToDev
        environment: 'DeployDev'
        strategy:
          runOnce:
            deploy:
              steps:
                - template: templates/deploy-template.yml
                  parameters:
                    appServiceName: 'mysitedev'
                    azureResourceServiceConnection: $(azureResourceServiceConnection)
                    imageRepository: $(imageRepository)
                    containerRegistry: $(containerRegistry)
                    resourceGroupName: $(resourceGroupName)

  - stage: DeployPro
    dependsOn: DeployDev
    displayName: 'Deploy to PRO'
    jobs:
      - deployment: DeployToPro
        environment: 'DeployPro'
        strategy:
          runOnce:
            deploy:
              steps:
                - template: templates/deploy-template.yml
                  parameters:
                    appServiceName: 'mysitepro'
                    azureResourceServiceConnection: $(azureResourceServiceConnection)
                    imageRepository: $(imageRepository)
                    containerRegistry: $(containerRegistry)
                    resourceGroupName: $(resourceGroupName)
