trigger:
  - develop

pool:
  vmImage: 'ubuntu-latest'

resources:
  - repo: self

parameters:
  - name: currentBranch
    type: string
  - name: appServiceName
    type: string

variables:
  projectId: '4c1f4cba-da43-4422-a077-8b7a47bb1cf2'
  buildPipelineId: '54'
  azureResourceServiceConnection: 'Azure Resource Manager Connection'
  imageRepository: 'mysitefrontend'
  containerRegistry: 'hasacr.azurecr.io'
  resourceGroupName: 'HasDev'

stages:
  - stage: Deploy
    displayName: 'Deploy to App Service'
    jobs:
      - deployment: DeployToAppService
        environment: 'DeployDev'
        strategy:
          runOnce:
            deploy:
              steps:
                - template: templates/deploy-template.yml
                  parameters:
                    appServiceName: $(appServiceName)
                    projectId: $(projectId)
                    buildPipelineId: $(buildPipelineId)
                    azureResourceServiceConnection: $(azureResourceServiceConnection)
                    imageRepository: $(imageRepository)
                    containerRegistry: $(containerRegistry)
                    resourceGroupName: $(resourceGroupName)
