trigger:
  branches:
    exclude:
      - "*"

pool:
  vmImage: "ubuntu-latest"

stages:
  - stage: CodeQuality
    displayName: "Code Quality and Testing"
    jobs:
      - job: RunChecks
        displayName: "Run Code Checks"
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: "20.x"
            displayName: "Install Node.js"

          - script: npm install
            displayName: "Install Project Dependencies"

          - script: npm run lint:prettier
            displayName: "Run Prettier Linter"

          - script: npm run test:coverage
            displayName: "Run Unit Tests with Coverage"

          - task: PublishTestResults@2
            displayName: "Publish Unit Test Results"
            condition: succeededOrFailed()
            inputs:
              testResultsFormat: "JUnit"
              testResultsFiles: "**/test-results/jest-junit.xml"
              mergeTestResults: true
              testRunTitle: "Unit Tests"
