trigger: none

pool:
  vmImage: 'ubuntu-latest'

resources:
  pipelines:
    - pipeline: azure-pipelines-CI
      source: FrontEnd/CI
      project: MySite
      trigger:
        branches:
          include:
            - develop

variables:
  azureResourceServiceConnection: 'Azure Resource Manager Connection'
  imageRepository: 'mysitefrontend'
  containerRegistry: 'hasacr.azurecr.io'
  resourceGroupName: 'HasDev'

stages:
  - stage: DeployDev
    displayName: 'Deploy to DEV'
    parameters:
      appServiceName: 'mysitedev'
    jobs:
      - template: templates/code-quality-template.yml

  - stage: DeployPro
    dependsOn: DeployDev
    displayName: 'Deploy to PRO'
    parameters:
      appServiceName: 'mysitepro'
    jobs:
      - template: templates/code-quality-template.yml
