trigger:
  branches:
    exclude:
      - "*"

pool:
  vmImage: "ubuntu-latest"

stages:
  - stage: CodeQuality
    displayName: "Code Quality and Testing"
    jobs:
      - template: code-quality-template.yml
