trigger: none

pool:
  vmImage: 'ubuntu-latest'

resources:
  pipelines:
    - pipeline: continuous-integration
      source: FrontEnd/ContinuousIntegration
      project: MySite
      trigger:
        branches:
          include:
            - develop

variables:
  appServiceName: 'mysitepro'
  azureResourceServiceConnection: 'Azure Resource Manager Connection'
  imageRepository: 'mysitefrontend'
  containerRegistry: 'hasacr.azurecr.io'
  resourceGroupName: 'HasDev'
  environmentName: 'DeployDev'
  environment: 'DEV'

stages:
  - stage: Deploy
    displayName: 'Deploy to $(environment)'
    jobs:
      - deployment: Deploy
        environment: $(environmentName)
        strategy:
          runOnce:
            deploy:
              steps:
                - template: templates/deploy-template.yml
                  parameters:
                    projectId: '4c1f4cba-da43-4422-a077-8b7a47bb1cf2'
                    buildPipelineId: '54'
                    appServiceName: $(appServiceName)
                    azureResourceServiceConnection: $(azureResourceServiceConnection)
                    imageRepository: $(imageRepository)
                    containerRegistry: $(containerRegistry)
                    resourceGroupName: $(resourceGroupName)
