trigger: master

pool:
  vmImage: 'ubuntu-latest'

variables:
  azureResourceServiceConnection: 'Azure Resource Manager Connection'
  imageRepository: 'mysitefrontend'
  containerRegistry: 'hasacr.azurecr.io'
  resourceGroupName: 'HasDev'
  environmentName: 'dev'
  appServiceName: 'mysitepro'

stages:
  - stage: Deploy
    displayName: 'Deploy to ${{ environmentName }}'
    jobs:
      - deployment: Deploy
        environment: ${{ environmentName }}
        strategy:
          runOnce:
            deploy:
              steps:
                - template: templates/deploy-template.yml
                  parameters:
                    appServiceName: ${{ appServiceName }}
                    environmentName: ${{ environmentName }}
                    projectId: '4c1f4cba-da43-4422-a077-8b7a47bb1cf2'
                    buildPipelineId: '54'
                    azureResourceServiceConnection: $(azureResourceServiceConnection)
                    imageRepository: $(imageRepository)
                    containerRegistry: $(containerRegistry)
                    resourceGroupName: $(resourceGroupName)
