trigger: none

pool:
  vmImage: 'ubuntu-latest'

resources:
  pipelines:
    - pipeline: continuous-delivery-dev
      source: FrontEnd/ContinuousDeliveryDev
      project: MySite
      trigger:
        branches:
          include:
            - master

variables:
  projectId: '4c1f4cba-da43-4422-a077-8b7a47bb1cf2'
  buildPipelineId: '63'
  appServiceName: 'mysitepro'
  azureResourceServiceConnection: 'Azure Resource Manager Connection'
  imageRepository: 'mysitefrontend'
  containerRegistry: 'hasacr.azurecr.io'
  resourceGroupName: 'HasDev'

stages:
  - stage: DowloadArtifact
    displayName: 'Download Artifact Version'
    jobs:
      - job: DowloadArtifact
        displayName: 'Download Version Artifact Dev'
        steps:
          - task: DownloadPipelineArtifact@2
            displayName: 'Download Build Artifact'
            inputs:
              buildType: 'specific'
              project: $(projectId)
              definition: $(buildPipelineId)
              buildVersionToDownload: 'latest'
              targetPath: '$(Pipeline.Workspace)'

          - script: |
              echo "Checking files in $(Pipeline.Workspace)/BuildId"
              ls -l $(Pipeline.Workspace)/BuildId
              buildId=$(cat $(Pipeline.Workspace)/BuildId/buildId.txt)
              echo "Build ID: $buildId"
              echo "##vso[task.setvariable variable=buildId]$buildId"
              echo "$(containerRegistry)/$(imageRepository):$buildId"
            displayName: 'Extract Build ID'

  - stage: CodeQuality
    displayName: 'Code Quality and Testing'
    jobs:
      - template: templates/code-quality-template.yml

  - stage: SetVersion
    dependsOn: CodeQuality
    jobs:
      - job: GitVersion
        displayName: 'Execute GitVersion'
        steps:
          - template: templates/execute-gitversion-template.yml
