trigger: none

pool:
  vmImage: 'ubuntu-latest'

resources:
  pipelines:
    - pipeline: continuous-integration
      source: FrontEnd/ContinuousIntegration
      project: MySite
      trigger:
        branches:
          include:
            - develop

variables:
  appServiceName: 'mysitepro'
  azureResourceServiceConnection: 'Azure Resource Manager Connection'
  imageRepository: 'mysitefrontend'
  containerRegistry: 'hasacr.azurecr.io'
  resourceGroupName: 'HasDev'
  projectId: '4c1f4cba-da43-4422-a077-8b7a47bb1cf2'
  buildPipelineId: '54'

stages:
  - stage: Deploy
    displayName: 'Deploy to DEV'
    jobs:
      - deployment: Deploy
        environment: 'DeployDev'
        strategy:
          runOnce:
            deploy:
              steps:
                - template: templates/deploy-template.yml
                  parameters:
                    projectId: $(projectId)
                    buildPipelineId: $(buildPipelineId)
                    appServiceName: $(appServiceName)
                    azureResourceServiceConnection: $(azureResourceServiceConnection)
                    imageRepository: $(imageRepository)
                    containerRegistry: $(containerRegistry)
                    resourceGroupName: $(resourceGroupName)

  - stage: ContinuousIntegrationMaster
    dependsOn: Deploy
    displayName: Continuous Integration Master
    jobs:
      - deployment: MergeApproval
        displayName: 'Approve and Merge to Master'
        environment: 'DeployPro'
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self
                  persistCredentials: true
                  fetchDepth: 0

                - script: |
                    echo "Switching to master branch"
                    git checkout master
                  displayName: 'Checkout Master Branch'

                - script: |
                    echo "Configuring Git"
                    git config user.name "Henk Sandoval"
                    git config user.email "henk.sandoval@outlook.com"
                  displayName: 'Configure Git User'

                - script: |
                    echo "Merging develop into master"
                    git merge origin/develop
                  displayName: 'Merge Develop into Master'

                - script: |
                    echo "Pushing changes"
                    git push origin master
                  displayName: 'Push Changes'
                  env:
                    SYSTEM_ACCESSTOKEN: $(System.AccessToken)

  - stage: PublishArtifact
    dependsOn: ContinuousIntegrationMaster
    displayName: 'Publish Build Artifact'
    jobs:
      - job: PublishBuildId
        displayName: 'Publish Build ID Artifact'
        steps:
          - task: DownloadPipelineArtifact@2
            displayName: 'Download Build Artifact'
            inputs:
              buildType: 'specific'
              project: $(projectId)
              definition: $(buildPipelineId)
              buildVersionToDownload: 'latest'
              targetPath: '$(Pipeline.Workspace)'

          - script: |
              echo "Checking files in $(Pipeline.Workspace)/BuildId"
              ls -l $(Pipeline.Workspace)/BuildId
              buildId=$(cat $(Pipeline.Workspace)/BuildId/buildId.txt)
              echo "Build ID: $buildId"
              echo "##vso[task.setvariable variable=buildId]$buildId"
              echo "$(containerRegistry)/$(imageRepository):$buildId"
            displayName: 'Extract Build ID'
