name: Create PR in Azure DevOps

on:
  push:
    branches: [develop]
  workflow_dispatch:

jobs:
  create-pr:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set Branch Name
      id: vars
      run: echo "BRANCH_NAME=feature/github-pr-$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV

    - name: Create New Branch
      env:
        AZURE_DEVOPS_PAT: ${{ secrets.AZURE_DEVOPS_PAT }}
      run: |
        curl -u :${{ secrets.AZURE_DEVOPS_PAT }} \
          -X POST \
          -H "Content-Type: application/json" \
          -d "{
            \"name\": \"refs/heads/${{ env.BRANCH_NAME }}\",
            \"oldObjectId\": \"$(git rev-parse origin/develop)\"
          }" \
          https://hsandoval.visualstudio.com/JobMagnetic/_apis/git/repositories/FrontEnd/refs?api-version=6.0

    - name: Push Changes to New Branch
      env:
        REPO_ACCESS_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}
      run: |
        git config --global user.email "you@example.com"
        git config --global user.name "Your Name"
        git remote set-url origin https://x-access-token:${REPO_ACCESS_TOKEN}@github.com/henksandoval/JobMagnetic-Site.git
        git push origin HEAD:${{ env.BRANCH_NAME }}

    - name: Create Pull Request
      env:
        AZURE_DEVOPS_PAT: ${{ secrets.AZURE_DEVOPS_PAT }}
      run: |
        curl -u :${{ secrets.AZURE_DEVOPS_PAT }} \
          -X POST \
          -H "Content-Type: application/json" \
          -d '{
            "sourceRefName": "refs/heads/${{ env.BRANCH_NAME }}",
            "targetRefName": "refs/heads/develop",
            "title": "Auto PR from GitHub",
            "description": "This pull request was automatically created from GitHub."
          }' \
          https://hsandoval.visualstudio.com/JobMagnetic/_apis/git/repositories/FrontEnd/pullrequests?api-version=6.0
